In [1]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv('HousePricePrediction.csv',usecols=['BldgType','LotConfig','TotalBsmtSF','SalePrice'])

In [7]:
df.head()

  LotConfig BldgType  TotalBsmtSF  SalePrice
0    Inside     1Fam        856.0   208500.0
1       FR2     1Fam       1262.0   181500.0
2    Inside     1Fam        920.0   223500.0
3    Corner     1Fam        756.0   140000.0
4       FR2     1Fam       1145.0   250000.0

In [8]:
df['BldgType'].unique()

array(['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs'], dtype=object)

In [ ]:
#exact numerical and categorical data into a single col
df['number_numerical']=pd.to_numeric(df['number'],errors='coerce',downcast='integer')

In [ ]:
#exact categorical data
df['number_categorical']=np.where(df['number_numerical'].isnull(),df['number'],np.nan)

In [16]:
#single row have numeric as well as categoric data
df['BldgType_num']=df['BldgType'].str.extract('(\d+)')#captures numerical part
df['BldgType_cat']=df['BldgType'].str[1:len(df['BldgType'])]# capture the first letter

In [18]:
df.sample(5)

     LotConfig BldgType  TotalBsmtSF  SalePrice BldgType_num BldgType_cat
2767    Corner   Duplex       1556.0        NaN          NaN        uplex
1824    Inside     1Fam        297.0        NaN            1          Fam
1038    Inside    Twnhs        546.0    97000.0          NaN         wnhs
2328    Inside     1Fam        915.0        NaN            1          Fam
1906    Corner     1Fam       1310.0        NaN            1          Fam