In [1]:
import numpy as np
import pandas as pd

In [4]:
date=pd.read_csv('Amazon Sale Report.csv',usecols=['Date','Status','Amount'])
# time=pd.read_csv('messages.csv')

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Date    128975 non-null  datetime64[ns]
 1   Status  128975 non-null  object
 2   Amount  121180 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 3.0+ MB

In [7]:
date['Date']=pd.to_datetime(date['Date'])

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_13204\4198805250.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date['Date']=pd.to_datetime(date['Date'])

In [10]:
date['date_year']=date['Date'].dt.year

In [11]:
date.head()

        Date                        Status  Amount  date_year
0 2022-04-30                     Cancelled  647.62       2022
1 2022-04-30  Shipped - Delivered to Buyer  406.00       2022
2 2022-04-30                       Shipped  329.00       2022
3 2022-04-30                     Cancelled  753.33       2022
4 2022-04-30                       Shipped  574.00       2022

In [12]:
date['date_month_name']=date['Date'].dt.month_name()

In [15]:
date.head()

,Date,Status,Amount,date_year,date_month_name,date_day
0,2022-04-30,Cancelled,647.62,2022,April,30
1,2022-04-30,Shipped - Delivered to Buyer,406.00,2022,April,30
2,2022-04-30,Shipped,329.00,2022,April,30
3,2022-04-30,Cancelled,753.33,2022,April,30
4,2022-04-30,Shipped,574.00,2022,April,30

In [14]:
date['date_day']=date['Date'].dt.day

In [19]:
#day of week
date['date_dow']=date['Date'].dt.dayofweek
#day of week name
date['date_dow_name']=date['Date'].dt.day_name()

In [20]:
date.head()

,Date,Status,Amount,date_year,date_month_name,date_day,date_dow,date_dow_name
0,2022-04-30,Cancelled,647.62,2022,April,30,5,Saturday
1,2022-04-30,Shipped - Delivered to Buyer,406.00,2022,April,30,5,Saturday
2,2022-04-30,Shipped,329.00,2022,April,30,5,Saturday
3,2022-04-30,Cancelled,753.33,2022,April,30,5,Saturday
4,2022-04-30,Shipped,574.00,2022,April,30,5,Saturday

In [21]:
#is _weekand?
date['date_is_weekand']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)

In [27]:
#Extract week of the year
date['date_week']=date['Date'].dt.isocalendar().week

In [30]:
#extract quater
date['qurater']=date['Date'].dt.quarter

In [32]:
date['semister']=np.where(date['qurater'].isin([1,2]),1,2)

In [34]:
#Extract Time elapsed btn two dates
import datetime
today=datetime.datetime.today()
today-date['Date']

0        1622 days 09:52:48.439602
1        1622 days 09:52:48.439602
2        1622 days 09:52:48.439602
3        1622 days 09:52:48.439602
4        1622 days 09:52:48.439602
                    ...
128970   1591 days 09:52:48.439602
128971   1591 days 09:52:48.439602
128972   1591 days 09:52:48.439602
128973   1591 days 09:52:48.439602
128974   1591 days 09:52:48.439602
Name: Date, Length: 128975, dtype: timedelta64[ns]

In [39]:
#month passed
date['months_diff'] = np.round(
    (today - date['Date']).dt.days / 30,
    0
)

In [ ]:
#time

time['date']=pd.to_datetime(time['date'])

In [ ]:
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second

In [ ]:
time['time']=time['date'].dt.time

In [ ]:
#time diff
today-time['date']

In [ ]:
#in sec
(today-time['date'])/np.timedelta64(1,'s')

In [ ]:
#in minutes
(today-time['date'])/np.timedelta64(1,'m')

In [ ]:
#in hours
(today-time['date'])/np.timedelta64(1,'h')